version: '3.8'
services:
  react-app:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/project/src:ro
    env_file:
      - ./.env
